### PR TITLE
Update Members.md

### PR DESCRIPTION
**Pull request by KevalPrajapati**
Added my intro.

### CODE REVIEW

**Review by jai-dewani — APPROVED** [review]
Looks good!

**Comment by KevalPrajapati** [comment]
> Looks good!

I messed up the last PR. So I created a new one.

**Comment by jai-dewani** [comment]
Yeah, No problem @KevalPrajapati :)

**Comment by ahammadshawki8** [comment]
There have been some updates to the members.md so make sure you update your forked repo and then update this PR to avoided merge conflicts

**Review by ahammadshawki8 — CHANGES_REQUESTED** [review]
There have been some updates to the members.md so make sure you update your forked repo and then update this PR to avoided merge conflicts

**Comment by KevalPrajapati** [comment]
Resolved merge conflicts.

**Pull request merged**
