### PR TITLE
Added details

### PR DESCRIPTION
**Pull request by rcoder23**
I am added my info.

### CODE REVIEW

**Comment by seema1711** [comment]
Please check this https://github.com/Bash-Woman-Community/Welcome/pull/7

**Review by rcoder23 — COMMENTED** [review]
Added my info and solve merge confilict . 
Thank you

**Comment by seema1711** [comment]
Please follow the template, and merge conflicts are not solved.

**Review by jai-dewani — CHANGES_REQUESTED** [review]
Hey @rcoder23    
There have been some updates to the `Members.md` so make sure you update your forked repo and then update this PR to avoided merge conflicts.

**Comment by rcoder23** [comment]
i am create new one .

**Pull request closed without merging**
