### PR TITLE
added member

### PR DESCRIPTION
**Pull request by Surajv311**
@jai-dewani .

### CODE REVIEW

**Review by jai-dewani — APPROVED** [review]
Looks Good!

**Comment by Surajv311** [comment]
I haven't received any invite, could you pls check? @jai-dewani

**Comment by jai-dewani** [comment]
The invite link to the discord server is in the README of this repo.

**Comment by Surajv311** [comment]
I've joined that. I meant the github org. invite @jai-dewani

**Comment by jai-dewani** [comment]
I guess If you did fill out the google form Seema shared in that tweet then she must have sent you the invitation

**Comment by seema1711** [comment]
@Surajv311 there are some conflicts in PR, please resolve them.

**Comment by Surajv311** [comment]
@seema1711 Done!

**Comment by ahammadshawki8** [comment]
There have been some updates to the members.md so make sure you update your forked repo and then update this PR to avoided merge conflicts

**Review by ahammadshawki8 — CHANGES_REQUESTED** [review]
There have been some updates to the members.md so make sure you update your forked repo and then update this PR to avoided merge conflicts

**Comment by plazzy99** [comment]
@Surajv311 you need to resolve your commit.

**Pull request closed without merging**
