### PR TITLE
Added my (Ahammad Shawki) intro and used bold text for the headings.

### PR DESCRIPTION
**Pull request by ahammadshawki8**
I used bold text for headings because otherwise, it is too hard to find the headings from the text. The bold text has made the __Headings__ eye-catchy.

### CODE REVIEW

**Comment by ahammadshawki8** [comment]
I guess pr#7 is closed. So, how can I refer to a closed pr?

**Comment by jai-dewani** [comment]
I think she ment refer to how I did it in #7

**Comment by ahammadshawki8** [comment]
I did exactly as you did in #7. In fact, you probably missed creating a new line for Tech Stack. I corrected that too.

**Comment by jai-dewani** [comment]
Oh Daam, Yeah. I missed that 🤦‍♂️ I think she will review this PR when she gets time

**Pull request merged**
