### PR TITLE
Introduction Ravi Bhagyoday

### PR DESCRIPTION
**Pull request by RaviBhagyoday**
Introduction Ravi Bhagyoday

### CODE REVIEW

**Comment by RaviBhagyoday** [comment]
Introduction Ravi Bhagyoday

**Review by jai-dewani — CHANGES_REQUESTED** [review]
Hey @RaviBhagyoday, Thanks for the PR. 
`About` and `Tech Stack` are supposed to be on newlines. Make sure you add 2 spaces at the end of each sentence to denote a new line in markdown files.

**Review by RaviBhagyoday — COMMENTED** [review]
Thanks Jai

**Review by jai-dewani — CHANGES_REQUESTED** [review]
Hey @RaviBhagyoday, 
The `About` line is still in the same line with `Country`, just make sure you check the preview before committing the changes. It helps a lot

**Review by jai-dewani — CHANGES_REQUESTED** [review]
Ahhh, how did I missed it earlier. 
There is a missing closing bracket in your Portfolio link

**Review by jai-dewani — APPROVED** [review]
Looks good @Bash-Woman-Community/maintainers

**Comment by ahammadshawki8** [comment]
There have been some updates to the members.md so make sure you update your forked repo and then update this PR to avoided merge conflicts.

**Review by ahammadshawki8 — CHANGES_REQUESTED** [review]
There have been some updates to the members.md so make sure you update your forked repo and then update this PR to avoided merge conflicts

**Comment by ahammadshawki8** [comment]
Great 👏🏼

**Pull request merged**
